/* Generated By:JJTree&JavaCC: Do not edit this line. ILOCParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ILOCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STACKPOINTERREGISTER = 6;
  /** RegularExpression Id. */
  int NORMALOPCODE = 7;
  /** RegularExpression Id. */
  int ASSIGN = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int CBR = 12;
  /** RegularExpression Id. */
  int JUMPL = 13;
  /** RegularExpression Id. */
  int JUMP = 14;
  /** RegularExpression Id. */
  int JUMPARROW = 15;
  /** RegularExpression Id. */
  int OPENSQUAREBRACKET = 16;
  /** RegularExpression Id. */
  int CLOSESQUAREBRACKET = 17;
  /** RegularExpression Id. */
  int REGISTER = 18;
  /** RegularExpression Id. */
  int LABEL = 19;
  /** RegularExpression Id. */
  int INTEGER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"rarp\"",
    "<NORMALOPCODE>",
    "\"=>\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"cbr\"",
    "\"jumpl\"",
    "\"jump\"",
    "\"->\"",
    "\"[\"",
    "\"]\"",
    "<REGISTER>",
    "<LABEL>",
    "<INTEGER>",
  };

}
