/* Generated By:JavaCC: Do not edit this line. ILOCParserTreeConstants.java Version 6.0_1 */
public interface ILOCParserTreeConstants
{
  public int JJTILOCPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTLABEL = 2;
  public int JJTNORMALOP = 3;
  public int JJTOPERAND = 4;
  public int JJTCONTROLFLOWOP = 5;


  public String[] jjtNodeName = {
    "ILOCProgram",
    "void",
    "LABEL",
    "NormalOp",
    "Operand",
    "ControlFlowOp",
  };
}
/* JavaCC - OriginalChecksum=6734b753f14b7a7a1a9a4086c9693e79 (do not edit this line) */
